name: "bluebell"
mode: "dev"
port: 8081
version: "v0.0.1"
start_time: "2022-01-01"
machine_id: 1

log:
  level: "debug"
  filename: "logfile.log"
  max_size: 200
  max_age: 30
  max_backups: 7

mysql:
  host: "127.0.0.1"
  port: "3306"
  user: "root"
  password: "root"
  dbname: "bluebell"
  max_open_conns:
  max_idle_conns:

redis:
  host: "127.0.0.1"
  port: 6379
  password: "123456"
  db: 0
  pool_size: 100